# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      #Install the required version of NodeJS
      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
          node-version: 16
            
      # Install the ACE CLI package
      - name: Install ACE CLI
        run: |
          curl -L -O https://github.com/ibm-watson-iis/ace-cli/releases/download/{1.4.0}/ace-cli-{Linux}-{x64}.tar.gz
          tar -xvf ace-cli-{Linux}-{x64}.tar.gz
          chmod +x ace
          sudo mv ace /usr/local/bin


